"""
Utility to update the version and app name in quizlet_converter_version.py.
This is useful for release automation or manual version bumps.
"""

import sys
import os

VERSION_FILE = os.path.join(os.path.dirname(__file__), "quizlet_converter_version.py")


def update_version(version, app_name="Quizleter"):
    content = f'''# filepath: quizlet_converter_version.py
# This file is auto-generated by version_converter.py or CI/CD
# Do not edit manually

__version__ = "{version}"
__app_name__ = "{app_name}"
'''
    with open(VERSION_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Updated {VERSION_FILE} to version {version} (app name: {app_name})")


def main():
    if len(sys.argv) < 2:
        print("Usage: python version_converter.py <version> [app_name]")
        sys.exit(1)
    version = sys.argv[1]
    app_name = sys.argv[2] if len(sys.argv) > 2 else "Quizleter"
    update_version(version, app_name)


if __name__ == "__main__":
    main()
